# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/query_expansion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pi/query_expansion.proto\x12\x03\x61pi\"\x1e\n\rExpandRequest\x12\r\n\x05query\x18\x01 \x01(\t\"8\n\x0e\x45xpandResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.api.ExpandResponseItem\":\n\x12\x45xpandResponseItem\x12\x10\n\x08\x65xpanded\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x32=\n\x06\x45xpand\x12\x33\n\x06\x45xpand\x12\x12.api.ExpandRequest\x1a\x13.api.ExpandResponse\"\x00\x62\x06proto3')



_EXPANDREQUEST = DESCRIPTOR.message_types_by_name['ExpandRequest']
_EXPANDRESPONSE = DESCRIPTOR.message_types_by_name['ExpandResponse']
_EXPANDRESPONSEITEM = DESCRIPTOR.message_types_by_name['ExpandResponseItem']
ExpandRequest = _reflection.GeneratedProtocolMessageType('ExpandRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXPANDREQUEST,
  '__module__' : 'api.query_expansion_pb2'
  # @@protoc_insertion_point(class_scope:api.ExpandRequest)
  })
_sym_db.RegisterMessage(ExpandRequest)

ExpandResponse = _reflection.GeneratedProtocolMessageType('ExpandResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXPANDRESPONSE,
  '__module__' : 'api.query_expansion_pb2'
  # @@protoc_insertion_point(class_scope:api.ExpandResponse)
  })
_sym_db.RegisterMessage(ExpandResponse)

ExpandResponseItem = _reflection.GeneratedProtocolMessageType('ExpandResponseItem', (_message.Message,), {
  'DESCRIPTOR' : _EXPANDRESPONSEITEM,
  '__module__' : 'api.query_expansion_pb2'
  # @@protoc_insertion_point(class_scope:api.ExpandResponseItem)
  })
_sym_db.RegisterMessage(ExpandResponseItem)

_EXPAND = DESCRIPTOR.services_by_name['Expand']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXPANDREQUEST._serialized_start=34
  _EXPANDREQUEST._serialized_end=64
  _EXPANDRESPONSE._serialized_start=66
  _EXPANDRESPONSE._serialized_end=122
  _EXPANDRESPONSEITEM._serialized_start=124
  _EXPANDRESPONSEITEM._serialized_end=182
  _EXPAND._serialized_start=184
  _EXPAND._serialized_end=245
# @@protoc_insertion_point(module_scope)
